from enum import Enum


class ReasonCode(str, Enum):
    # Existing
    LOW_STAKES_STABLE           = "LOW_STAKES_STABLE"
    SUFFICIENTLY_SPECIFIED      = "SUFFICIENTLY_SPECIFIED"
    STRUCTURALLY_CLEAR          = "STRUCTURALLY_CLEAR"
    MISSING_CONSTRAINTS         = "MISSING_CONSTRAINTS"
    AMBIGUOUS_INTENT            = "AMBIGUOUS_INTENT"
    INCOMPLETE_PREMISE          = "INCOMPLETE_PREMISE"
    FRESHNESS_SENSITIVE         = "FRESHNESS_SENSITIVE"
    FACTUAL_UNCERTAINTY         = "FACTUAL_UNCERTAINTY"
    EXTERNAL_DEPENDENCY         = "EXTERNAL_DEPENDENCY"
    SAFETY_ENVELOPE_TRIGGERED   = "SAFETY_ENVELOPE_TRIGGERED"
    INADMISSIBLE_REQUEST        = "INADMISSIBLE_REQUEST"
    INSUFFICIENT_GROUNDS        = "INSUFFICIENT_GROUNDS"

    # v7.5 KVS codes
    KVS_PASS_LOW_TVS_HIGH_MKR   = "KVS_PASS_LOW_TVS_HIGH_MKR"
    KVS_FAIL_TVS                = "KVS_FAIL_TVS"
    KVS_FAIL_MKR_PRIOR          = "KVS_FAIL_MKR_PRIOR"
    KVS_DOWNREV_FRESH           = "KVS_DOWNREV_FRESH"
    KVS_DOWNREV_HIST            = "KVS_DOWNREV_HIST"
    KVS_STABLE_BLOCKED          = "KVS_STABLE_BLOCKED"

    # v7.5 Phase B — V_regen
    VREGEN_STABLE               = "VREGEN_STABLE"
    VREGEN_UNSTABLE             = "VREGEN_UNSTABLE"
    KVS_DYNAMIC_DOWNREV         = "KVS_DYNAMIC_DOWNREV"
    # v7.5 Phase B — C_conflict (Phase B.2, future)
    CCONFLICT_CONSISTENT        = "CCONFLICT_CONSISTENT"
    CCONFLICT_CONFLICT          = "CCONFLICT_CONFLICT"
    # v7.5 Phase B — H_pred (Phase B.3, future)
    HPRED_LOW                   = "HPRED_LOW"
    HPRED_HIGH                  = "HPRED_HIGH"
    # v7.5 RGC codes
    RGC_ESCALATE_SELFCHECK      = "RGC_ESCALATE_SELFCHECK"
    RGC_ESCALATE_VERIFY         = "RGC_ESCALATE_VERIFY"
    RGC_BAND_ANSWER             = "RGC_BAND_ANSWER"
    RGC_BAND_SELFCHECK          = "RGC_BAND_SELFCHECK"
    RGC_BAND_VERIFY             = "RGC_BAND_VERIFY"

    # Phase G.8 — upstream signal repair
    DEFINITIONAL_QUERY          = "DEFINITIONAL_QUERY"
    DEFINITIONAL_NEEDS_EVIDENCE = "DEFINITIONAL_NEEDS_EVIDENCE"
    ADOPTION_MULTI_SIGNAL       = "ADOPTION_MULTI_SIGNAL"

    # Phase G.9 — finish-stage polish
    TECHNICAL_TERM_CANONICALIZED        = "TECHNICAL_TERM_CANONICALIZED"
    TECHNICAL_TERM_UNMAPPED_FALLBACK    = "TECHNICAL_TERM_UNMAPPED_FALLBACK"
    CONTINUITY_INTENT_DETECTED          = "CONTINUITY_INTENT_DETECTED"
    CONTINUITY_MANUAL_SAVE_TRIGGERED    = "CONTINUITY_MANUAL_SAVE_TRIGGERED"
    CONTINUITY_SAVE_INTENT_BLOCKED_OO   = "CONTINUITY_SAVE_INTENT_BLOCKED_OPT_OUT"
    REFLECTIVE_TAIL_SUPPRESSED_TECHNICAL = "REFLECTIVE_TAIL_SUPPRESSED_TECHNICAL"
