"""
query_reformulator.py — Search-optimized query reformulation.

Reformulates user queries into search-optimized keywords:
- en_keywords: for FAISS Wikipedia search (English index)
- native_keywords: for web search (Brave, Kiwix)

Single LLM call per query. Results live only within the turn (quarantine-scoped; never promoted to durable knowledge).

Phase G.9 adds a narrow canonical-term normalizer that preempts the
LLM's literal-translation failures on short technical queries (e.g.
"ユニット射" -> "unit shooting"). The map is small and inspectable;
unknown terms fall back to the LLM path unchanged.

Author : Taiko Toeda / MOBIUS LLC (generated by Claude Code)
License: AGPL-3.0-or-later
"""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

logger = logging.getLogger(__name__)


# ── Phase G.9 — canonical technical-term map ────────────────────────────────
#
# Keep this map SMALL, narrowly scoped to high-risk literal-translation
# failures (observed in the 40-turn eval). Each entry is:
#   <source surface (JA/ZH/etc.)> -> <canonical English term>
#
# Additions should be: (a) well-established canonical English, and
# (b) short enough that the LLM reformulator tends to get them wrong.
# Broad translation belongs to the LLM path.
CANONICAL_TECHNICAL_TERMS: dict[str, str] = {
    # ── Category theory ───────────────────────────────────────────
    "モナド":           "monad",
    "自然変換":         "natural transformation",
    "ユニット射":       "unit morphism",
    "カウニット":       "counit",
    "カウニット射":     "counit morphism",
    "クライスリ圏":     "Kleisli category",
    "アイレンベルグ・ムーア圏": "Eilenberg-Moore category",
    "関手":             "functor",
    "忘却関手":         "forgetful functor",
    "自由関手":         "free functor",
    "随伴関手":         "adjoint functor",
    "随伴":             "adjunction",
    "圏":               "category",
    "対象":             "object (category theory)",
    "射":               "morphism",
    "モノイド対象":     "monoid object",
    "終対象":           "terminal object",
    "始対象":           "initial object",
    "余極限":           "colimit",
    "極限":             "limit (category theory)",
    # ── Type theory / functional programming adjacent ─────────────
    "モナド則":         "monad laws",
    "ファンクタ":       "functor",
    "アプリカティブ":   "applicative functor",
    # ── Phase G.11 — broader math / physics / CS coverage ─────────
    # Linear algebra / math
    "固有値":           "eigenvalue",
    "固有ベクトル":     "eigenvector",
    "行列":             "matrix (mathematics)",
    "テンソル":         "tensor",
    "ヤコビアン":       "Jacobian matrix",
    "リー代数":         "Lie algebra",
    "リー群":           "Lie group",
    "群論":             "group theory",
    "位相空間":         "topological space",
    "ホモロジー":       "homology (mathematics)",
    "コホモロジー":     "cohomology",
    # Physics
    "量子もつれ":       "quantum entanglement",
    "波動関数":         "wave function",
    "シュレーディンガー方程式": "Schrödinger equation",
    "相対性理論":       "theory of relativity",
    # Computer science / ML
    "注意機構":         "attention mechanism",
    "トランスフォーマー": "transformer (machine learning)",
    "畳み込みニューラルネットワーク": "convolutional neural network",
    "誤差逆伝播":       "backpropagation",
    "勾配降下法":       "gradient descent",
    "強化学習":         "reinforcement learning",
    # Algorithms / CS theory
    "動的計画法":       "dynamic programming",
    "チューリングマシン": "Turing machine",
    "計算可能性":       "computability",
    "決定性有限オートマトン": "deterministic finite automaton",
}


# Phase G.11 — domain anchors for disambiguation.
#
# Maps a canonical-term source to the domain it belongs to. When the
# reformulator sees a term like "カウニット" in a session whose themes
# also match the domain, we can confidently surface the canonical
# English term with an explicit domain hint in the en_keywords so
# Wiki/search disambiguates correctly (preventing "counter"-style
# drift).
CANONICAL_TERM_DOMAIN: dict[str, str] = {
    # Category theory
    "モナド":           "category theory",
    "自然変換":         "category theory",
    "ユニット射":       "category theory",
    "カウニット":       "category theory",
    "カウニット射":     "category theory",
    "クライスリ圏":     "category theory",
    "アイレンベルグ・ムーア圏": "category theory",
    "関手":             "category theory",
    "忘却関手":         "category theory",
    "自由関手":         "category theory",
    "随伴関手":         "category theory",
    "随伴":             "category theory",
    "圏":               "category theory",
    "対象":             "category theory",
    "射":               "category theory",
    "モノイド対象":     "category theory",
    "終対象":           "category theory",
    "始対象":           "category theory",
    "余極限":           "category theory",
    "極限":             "category theory",
    "モナド則":         "category theory",
    "ファンクタ":       "category theory",
    "アプリカティブ":   "category theory",
    # Linear algebra / math
    "固有値":           "linear algebra",
    "固有ベクトル":     "linear algebra",
    "行列":             "linear algebra",
    "テンソル":         "tensor mathematics",
    "ヤコビアン":       "multivariable calculus",
    "リー代数":         "Lie theory",
    "リー群":           "Lie theory",
    "群論":             "abstract algebra",
    "位相空間":         "topology",
    "ホモロジー":       "algebraic topology",
    "コホモロジー":     "algebraic topology",
    # Physics
    "量子もつれ":       "quantum mechanics",
    "波動関数":         "quantum mechanics",
    "シュレーディンガー方程式": "quantum mechanics",
    "相対性理論":       "physics",
    # CS / ML
    "注意機構":         "machine learning",
    "トランスフォーマー": "machine learning",
    "畳み込みニューラルネットワーク": "machine learning",
    "誤差逆伝播":       "machine learning",
    "勾配降下法":       "machine learning",
    "強化学習":         "machine learning",
    "動的計画法":       "algorithms",
    "チューリングマシン": "theory of computation",
    "計算可能性":       "theory of computation",
    "決定性有限オートマトン": "theory of computation",
}


def canonical_term_domain_hint(hits: Optional[List[str]]) -> str:
    """Phase G.11 — domain-anchor hint for retrieval disambiguation.

    Given canonical_hits, returns the dominant domain string (most
    frequent domain across the hits). Empty string when nothing to
    anchor. Pure function.
    """
    if not hits:
        return ""
    counts: dict[str, int] = {}
    for h in hits:
        d = CANONICAL_TERM_DOMAIN.get(h)
        if d:
            counts[d] = counts.get(d, 0) + 1
    if not counts:
        return ""
    # Return the single most-frequent domain (tie: first seen).
    best = max(counts.items(), key=lambda kv: kv[1])
    return best[0]


def canonical_term_hint_from_hits(canonical_hits: Optional[List[str]]) -> str:
    """Phase G.10 — narrow synthesis-side canonical hint.

    Given the `canonical_hits` list produced by `_canonicalize_technical_terms`
    (surface source terms like "ユニット射"), return a short, inspectable
    one-liner that the synthesis prompt can include to anchor the model
    on the correct canonical English term. Empty string when nothing to
    hint.

    Example output (when hits=["ユニット射", "カウニット"]):
        'ユニット射 = unit morphism; カウニット = counit'

    Intentionally non-overbearing: the hint is NOT a translation
    instruction, only a glossary note the model can consult. Callers
    should gate use of this hint on a clearly technical/definitional
    context so non-technical chat is not polluted.
    """
    if not canonical_hits:
        return ""
    parts: List[str] = []
    for src in canonical_hits:
        canonical = CANONICAL_TECHNICAL_TERMS.get(src)
        if canonical:
            parts.append(f"{src} = {canonical}")
    return "; ".join(parts)


def _canonicalize_technical_terms(query: str) -> Tuple[str, List[str]]:
    """Phase G.9 — narrow canonical-term substitution.

    For each entry in `CANONICAL_TECHNICAL_TERMS`, if the source string
    appears in `query`, return a reformulated text where the occurrence
    is replaced by its canonical English form. Also returns the list of
    matched source terms (inspectable for reason-note surfacing).

    Pure function. Does NOT translate anything outside the map. If no
    mapping fires, returns the original query unchanged.
    """
    if not query:
        return query, []
    hits: List[str] = []
    out = query
    # Apply longest-first to avoid partial-overlap surprises
    # (e.g. "カウニット射" must match before "カウニット").
    for src in sorted(CANONICAL_TECHNICAL_TERMS.keys(),
                       key=lambda s: -len(s)):
        if src and src in out:
            out = out.replace(src, CANONICAL_TECHNICAL_TERMS[src])
            hits.append(src)
    return out, hits


@dataclass
class ReformulatedQuery:
    """Result of query reformulation."""
    original: str
    en_keywords: str
    native_keywords: str
    lang: str
    # Phase G.9 — inspectable canonicalization notes.
    canonical_hits: List[str] = field(default_factory=list)
    notes:          List[str] = field(default_factory=list)


def reformulate_query(
    query: str,
    lang: str,
    adapter=None,
    ollama_endpoint: str = "http://localhost:11434",
    ollama_model: str = "qwen3.5:9b",
) -> ReformulatedQuery:
    """Reformulate a user query into search-optimized keywords.

    Args:
        query: Original user query.
        lang: Detected language code ("ja", "zh", "en", etc.).
        adapter: InferenceAdapter with generate() method. If None,
                 uses direct Ollama HTTP call.
        ollama_endpoint: Ollama endpoint (used when adapter is None).
        ollama_model: Ollama model name (used when adapter is None).

    Returns:
        ReformulatedQuery with en_keywords and native_keywords.
        On failure, returns original query as both keywords.

    Phase G.9: prior to LLM reformulation, a narrow canonical-term
    substitution pass normalizes known technical terms to their English
    canonical form (e.g. "ユニット射" -> "unit morphism"). This
    preempts common literal-translation failures observed in the real
    dialogue eval. Unknown terms are unaffected.
    """
    # Phase G.9 canonicalization — applied universally, cheap, idempotent.
    canonical_query, canonical_hits = _canonicalize_technical_terms(query)
    notes: List[str] = []
    if canonical_hits:
        notes.append("technical_term_canonicalized")
        notes.append(f"terms={canonical_hits}")
    elif query and not canonical_query == query:
        notes.append("technical_term_unmapped_fallback")

    if lang == "en":
        rq = _reformulate_english(
            canonical_query, adapter, ollama_endpoint, ollama_model,
        )
    else:
        rq = _reformulate_multilingual(
            canonical_query, lang, adapter, ollama_endpoint, ollama_model,
        )
    # Preserve the ORIGINAL user query on the result for trace purposes
    # (the LLM saw the canonicalized form, but native_keywords should
    # prefer the user's own language where possible).
    rq.original = query
    rq.canonical_hits = canonical_hits
    rq.notes = notes
    # For non-English: if we canonicalized, append the canonical terms
    # to en_keywords so Box W/wiki search has strong signal even if the
    # LLM's English output missed them.
    if canonical_hits and lang != "en":
        extras = " ".join(CANONICAL_TECHNICAL_TERMS[k] for k in canonical_hits)
        if extras and extras.lower() not in rq.en_keywords.lower():
            rq.en_keywords = f"{rq.en_keywords} {extras}".strip()
    # Phase G.11 — domain-anchor hint. If the canonical hits agree on a
    # dominant domain, append that domain phrase to en_keywords. This
    # disambiguates short technical terms during Wiki / web search
    # (e.g. "counit" alone can drift to counter/electronics; "counit
    # category theory" is unambiguous).
    if canonical_hits:
        domain = canonical_term_domain_hint(canonical_hits)
        if domain and domain.lower() not in rq.en_keywords.lower():
            rq.en_keywords = f"{rq.en_keywords} {domain}".strip()
            rq.notes.append(f"domain_anchor={domain}")
    return rq


def _reformulate_english(
    query: str, adapter, endpoint: str, model: str,
) -> ReformulatedQuery:
    """Reformulate English query into search keywords.

    v0.1-rc2 calibration: `native_keywords` is set to the LLM-rewritten
    keywords (same as `en_keywords`) so that BOX S (web search) on
    English queries receives a normalized keyword string instead of the
    raw user prompt. The Phase 5C / P9 normalization wiring audit
    identified the prior `native_keywords = query` choice as an
    English-side asymmetry: non-English queries already get a distinct
    normalized `native_keywords` from `_reformulate_multilingual`.

    Freshness / TVS-HIGH branches at the BOX S call sites still
    intentionally override with `f"{search_query} {date}"` (RCB_1), so
    the calibration does not affect freshness-sensitive paths.
    """
    prompt = (
        "Generate 3-5 optimal English search keywords for this question. "
        "Output ONLY the keywords separated by spaces, no explanation.\n\n"
        f"Question: {query}"
    )
    result = _call_llm(prompt, adapter, endpoint, model)
    en_kw = result.strip() if result else query
    return ReformulatedQuery(
        original=query,
        en_keywords=en_kw,
        # rc2 calibration: was `native_keywords=query`; now mirror
        # en_keywords so BOX S receives normalized text on English.
        native_keywords=en_kw,
        lang="en",
    )


def _reformulate_multilingual(
    query: str, lang: str, adapter, endpoint: str, model: str,
) -> ReformulatedQuery:
    """Reformulate non-English query into both English and native keywords."""
    prompt = (
        f"You are a search query optimizer. Given a question in {lang}, generate:\n"
        "1. English search keywords (3-5 words) optimized for Wikipedia search\n"
        "2. Original language search keywords (3-5 words) optimized for web search\n\n"
        "Output format (exactly 2 lines, no labels, no numbering):\n"
        "english keywords here\n"
        "原言語キーワード here\n\n"
        f"Question: {query}"
    )
    result = _call_llm(prompt, adapter, endpoint, model)
    if not result:
        return ReformulatedQuery(
            original=query, en_keywords=query, native_keywords=query, lang=lang,
        )

    lines = [l.strip() for l in result.strip().split("\n") if l.strip()]
    en_kw = lines[0] if len(lines) >= 1 else query
    native_kw = lines[1] if len(lines) >= 2 else query

    # Sanity check: if en_keywords contains CJK, swap or use original
    if _has_cjk(en_kw) and len(lines) >= 2 and not _has_cjk(lines[1]):
        en_kw, native_kw = lines[1], lines[0]
    elif _has_cjk(en_kw):
        en_kw = query  # Fallback

    return ReformulatedQuery(
        original=query, en_keywords=en_kw, native_keywords=native_kw, lang=lang,
    )


def _has_cjk(text: str) -> bool:
    """Check if text contains CJK characters."""
    for ch in text:
        cp = ord(ch)
        if (0x3040 <= cp <= 0x9FFF or 0xF900 <= cp <= 0xFAFF
                or 0x4E00 <= cp <= 0x9FFF):
            return True
    return False


def _call_llm(
    prompt: str, adapter, endpoint: str, model: str,
) -> str | None:
    """Call LLM for query reformulation. Returns text or None."""
    # Try adapter first
    if adapter is not None:
        try:
            from src.adapters.inference_adapter import KernelRequest
            req = KernelRequest(user_input=prompt, prompt=prompt)
            resp = adapter.generate(req)
            if resp and resp.text:
                return resp.text.strip()
        except Exception as e:
            logger.debug(f"[QueryReformulator] Adapter call failed: {e}")

    # Direct Ollama call
    try:
        import httpx
        resp = httpx.post(
            f"{endpoint}/api/generate",
            json={
                "model": model,
                "prompt": prompt,
                "stream": False,
                "think": False,
                "options": {"temperature": 0.0, "num_predict": 80},
            },
            timeout=15.0,
        )
        resp.raise_for_status()
        return resp.json().get("response", "").strip()
    except Exception as e:
        logger.debug(f"[QueryReformulator] Ollama call failed: {e}")
        return None
