#!/usr/bin/env python3
"""stability_sim.py — Phase 3 Stab Commit 47.

Cross-run variance assessment for the 33-scenario harness. Runs the
harness N times per mode (default / selective / full) and reports
mean / stdev / range / variance% per mode. Intended for daily
stability monitoring or release-gate sanity check.

Methodology:
- Each run is a fresh subprocess invocation of run_33_scenarios.py,
  which itself spawns scenario_runner.py — that subprocess boundary
  resets the ME5 singleton and any in-process caches, simulating a
  cold-cache run-to-run condition equivalent to a daily restart.
- For per-process warm-cache profiling, use --warm; for cold-cache
  (default behavior), each run pays the ~5s ME5 load cost.

Output:
- Aggregate JSON: per-mode {mean, stdev, min, max, variance_pct,
  per-run results}
- Markdown report at --report path

Variance % = stdev / mean × 100. Spec gate: variance% < 6.5%
(approx 2σ at σ=0.65 around mean=31; equivalent to "stable" rating).

Spec ref: PATTERN_LIBRARY_SPEC_v1_4_1.md §7.8.7 (informational pass
criteria) + §7.8.6.1 (Phase 3 stab N=5 empirical refinement).
"""
from __future__ import annotations

import argparse
import json
import os
import statistics
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RUN_HARNESS = REPO_ROOT / "scripts" / "run_33_scenarios.py"


MODES = {
    "default": {},  # no env vars
    "selective": {"MOBIUS_PATTERN_LIBRARY_PRIMARY_SELF_REF": "1",
                   "MOBIUS_PATTERN_LIBRARY": "1"},
    "full": {"MOBIUS_PATTERN_LIBRARY_FULL_PRIMARY": "1",
              "MOBIUS_PATTERN_LIBRARY": "1"},
}


def _summarize(values: list[int]) -> dict:
    if not values:
        return {"n": 0}
    n = len(values)
    mean = sum(values) / n
    sd = statistics.stdev(values) if n >= 2 else 0.0
    return {
        "n": n,
        "values": values,
        "mean": mean,
        "stdev": sd,
        "min": min(values),
        "max": max(values),
        "range": max(values) - min(values),
        "variance_pct": (sd / mean * 100.0) if mean else 0.0,
    }


def run_mode(mode: str, n_runs: int, output_dir: Path) -> dict:
    env_vars = MODES[mode]
    print(f"[stability_sim] mode={mode} n_runs={n_runs} env={env_vars}")
    output_path = output_dir / f"stability_{mode}_n{n_runs}.json"
    cmd = [
        "python3", str(RUN_HARNESS),
        "--n-runs", str(n_runs),
        "--quiet",
        "--output", str(output_path),
    ]
    env = os.environ.copy()
    for k, v in env_vars.items():
        env[k] = v
    proc = subprocess.run(cmd, env=env, cwd=REPO_ROOT,
                          capture_output=True, text=True,
                          timeout=3600 * 2)  # up to 2h for N>=3
    if proc.returncode != 0:
        print(f"[stability_sim] {mode} run had non-zero exit "
              f"{proc.returncode}", file=sys.stderr)
        print(proc.stderr[:1000], file=sys.stderr)
    if not output_path.exists():
        return {"mode": mode, "error": "no_output_json",
                "stderr": proc.stderr[:500]}

    payload = json.loads(output_path.read_text(encoding="utf-8"))
    summary = payload.get("summary", {})
    values = summary.get("passed_per_run", [])
    aggregated = _summarize(values)
    aggregated["mode"] = mode
    aggregated["max_leakage"] = summary.get("max_leakage", 0)
    aggregated["raw_path"] = str(output_path)
    return aggregated


def render_report(per_mode: dict, gate_variance_pct: float = 6.5) -> str:
    lines = [
        "# Phase 3 Stab Cross-Run Variance Report",
        "",
        f"_Generated by `scripts/stability_sim.py`. Variance gate: "
        f"< {gate_variance_pct}% (≈ 2σ at σ=0.65 / mean=31)._",
        "",
        "## Per-mode summary",
        "",
        "| Mode | N | Mean | Stdev | Min | Max | Range | Variance % | Stable? |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for mode, info in per_mode.items():
        n = info.get("n", 0)
        mean = info.get("mean", 0)
        sd = info.get("stdev", 0)
        lo = info.get("min", "—")
        hi = info.get("max", "—")
        rng = info.get("range", "—")
        v = info.get("variance_pct", 0)
        stable = "✓" if v < gate_variance_pct else "✗"
        lines.append(
            f"| {mode} | {n} | {mean:.2f} | {sd:.2f} | {lo} | {hi} | "
            f"{rng} | {v:.2f}% | {stable} |"
        )
    lines.extend([
        "",
        "## Per-mode raw values",
        "",
    ])
    for mode, info in per_mode.items():
        vals = info.get("values", [])
        lines.append(f"- **{mode}**: {vals}")
    lines.extend([
        "",
        "## Methodology",
        "",
        "Each run is a fresh subprocess of run_33_scenarios.py + ",
        "scenario_runner.py. The subprocess boundary resets the ME5 ",
        "singleton, providing cold-cache behavior equivalent to a daily ",
        "process restart. The cumulative cold-load cost per run is ",
        "approximately 5 s; remaining time is qwen3.5:9b synthesis.",
        "",
        "Variance % is interpreted relative to a stochastic floor σ ≈ 0.65 ",
        "(spec v1.4.1 §7.8.6.1). Variance ≈ σ/mean × 100. At mean=31, ",
        "the floor σ=0.65 corresponds to ~2.1% variance; the spec gate ",
        f"{gate_variance_pct}% allows roughly 3σ headroom.",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run cross-mode stability simulation "
                     "(N runs × 3 modes)."
    )
    parser.add_argument(
        "--n-runs", type=int, default=3,
        help="N runs per mode (default 3).",
    )
    parser.add_argument(
        "--modes", nargs="+", default=list(MODES.keys()),
        choices=list(MODES.keys()),
        help="Modes to measure (default: all 3).",
    )
    parser.add_argument(
        "--output-dir", type=Path,
        default=Path("/tmp/phase3_stab_variance"),
        help="Output directory for raw JSON + summary.",
    )
    parser.add_argument(
        "--report", type=Path,
        default=REPO_ROOT / "docs" / "PHASE_3_STAB_VARIANCE_REPORT.md",
        help="Markdown report destination.",
    )
    parser.add_argument(
        "--gate", type=float, default=6.5,
        help="Variance %% gate (default 6.5).",
    )
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    per_mode: dict[str, dict] = {}
    for mode in args.modes:
        result = run_mode(mode, args.n_runs, args.output_dir)
        per_mode[mode] = result
        print(f"[stability_sim] {mode}: mean={result.get('mean'):.2f} "
              f"σ={result.get('stdev'):.2f} variance={result.get('variance_pct'):.2f}%")

    summary_path = args.output_dir / "summary.json"
    summary_path.write_text(
        json.dumps(per_mode, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    md = render_report(per_mode, gate_variance_pct=args.gate)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(md, encoding="utf-8")
    print(f"\n[stability_sim] Report: {args.report}")
    print(f"[stability_sim] Summary: {summary_path}")

    # Exit code: 0 if all modes within variance gate, 1 otherwise
    failures = [m for m, info in per_mode.items()
                if info.get("variance_pct", float("inf")) >= args.gate]
    return 0 if not failures else 1


if __name__ == "__main__":
    raise SystemExit(main())
